// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrVDaQsOsEtjEmxWn74xj4sUtg3QIqRGU',
    appId: '1:10338903210:web:829a4638246fff614f1cd3',
    messagingSenderId: '10338903210',
    projectId: 'mini-crm-project-40646',
    authDomain: 'mini-crm-project-40646.firebaseapp.com',
    storageBucket: 'mini-crm-project-40646.firebasestorage.app',
    measurementId: 'G-PB7DS1LSEH',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrVDaQsOsEtjEmxWn74xj4sUtg3QIqRGU',
    appId: '1:10338903210:web:47cd8b9a0a3f25f64f1cd3',
    messagingSenderId: '10338903210',
    projectId: 'mini-crm-project-40646',
    authDomain: 'mini-crm-project-40646.firebaseapp.com',
    storageBucket: 'mini-crm-project-40646.firebasestorage.app',
    measurementId: 'G-794KD81TZ2',
  );
}
